spring.application.name=regione-abruzzo

springdoc.swagger-ui.path=/swagger-ui.html

spring.datasource.url=jdbc:mariadb://localhost:3306/regione_abruzzo
spring.datasource.username=root
spring.datasource.password=mariadb
spring.datasource.driver-class-name=org.mariadb.jdbc.Driver

#TODO da chiedere se saliamo con degli script
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.MariaDBDialect


logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.orm.jdbc.bind=TRACE

# Proprieta Personalizzate per JWT e Regione Abruzzo
jwt.secret=M0E0Y2stU2VjcmV0LUtleS1Gb3ItSldULUdlbmVyYXRpb24tU3ByaW5nLUJvb3QtM2V4cHJlc3M=
regione.abruzzo.ratichet.url=https://coll-api.regione.abruzzo.it/v1/accreditamento
regione.abruzzo.ratichet.token=MOCK_DEV_TOKEN_ABRUZZO