spring.application.name=regione-abruzzo

springdoc.swagger-ui.path=/swagger-ui.html

spring.datasource.url=jdbc:mariadb://localhost:3306/regione_abruzzo
spring.datasource.username=root
spring.datasource.password=mariadb
spring.datasource.driver-class-name=org.mariadb.jdbc.Driver

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.MariaDBDialect

logging.level.org.springframework.security=DEBUG
logging.level.org.springframework.web.client.RestTemplate=DEBUG
logging.level.org.springframework.web.servlet.DispatcherServlet=DEBUG

# ==========================================
# LOGIN SPID DEMO AGID - OIDC
# ==========================================
spring.security.oauth2.client.registration.spid.client-id=demo-spid-client-test
spring.security.oauth2.client.registration.spid.client-secret=demo-spid-secret-test
spring.security.oauth2.client.registration.spid.scope=openid,profile,email
spring.security.oauth2.client.registration.spid.authorization-grant-type=authorization_code
spring.security.oauth2.client.registration.spid.redirect-uri={baseUrl}/login/oauth2/code/spid

spring.security.oauth2.client.provider.spid.authorization-uri=https://demo.spid.gov.it/openid/authorize
spring.security.oauth2.client.provider.spid.token-uri=https://demo.spid.gov.it/openid/token
spring.security.oauth2.client.provider.spid.user-info-uri=https://demo.spid.gov.it/openid/userinfo
spring.security.oauth2.client.provider.spid.jwk-set-uri=https://demo.spid.gov.it/openid/jwks
spring.security.oauth2.client.provider.spid.user-name-attribute=sub

# ==========================================
# ADFS REGIONE ABRUZZO - TOKEN M2M
# ==========================================
ra.adfs.token-url=https://adfs.regione.abruzzo.it/adfs/oauth2/token
ra.adfs.client-id=xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx
ra.adfs.client-secret=test
ra.adfs.scope=https://govway-dev.regione.abruzzo.it

# ==========================================
# RAAuth Gateway
# ==========================================
ra.auth.get-data-url=https://raauth2-dev.regione.abruzzo.it/data/getData/

# Da verificare quale usare per CMP.
ra.auth.app-code=000022

ra.ticket.service-url=https://raticket-be-dev.regione.abruzzo.it
ra.ticket.new-ticket-path=raticketv2/ticket/nuovoTicket